export const projectList = [
    {
        title: 'v2.0-Eatery',
        startDate: '2023-08-01',
        endDate: '2023-11-30',
        skills: [
            'Typescript',
            'Next.js',
            'ReactNative',
            'redux-toolkit',
            'react-query',
            'Emotion',
            'Git',
            'Github',
            'Jira',
        ],
        contents: [
            '네이버 지도 API를 활용한 POI 탐색',
            '업종/기간/지역별 필터링 기능 구현',
            '예약/주문 이력에 대한 데이터 시각화',
            '지역 기반 마커 클러스터링 구현',
            'atomic design system 기반의 컴포넌트 구현',
            'storybook을 활용한 컴포넌트 UI 테스트',
            'dynamic routing을 활용한 지도 url 공유 기능 구현',
            'chrome, safari, firefox, opera에 대한 크로스브라우징 테스트',
            '미디어쿼리를 이용한 반응형/적응형 구현',
        ],
    },
    {
        title: 'v1.0-Eatery',
        startDate: '2022-10-01',
        endDate: '2023-07-31',
        skills: ['Typescript', 'ReactNative', 'recoil', 'styled-components', 'Git', 'Github'],
        contents: [
            '기존 option api에서 Vue3 composition api으로 마이그레이션',
            '기존 atomic 시스템 기반의 스토리북 구조에서 컴포넌트 종류에 따른 구조로 변환',
            '컴포넌트 css 수정 및 기능 추가 개발',
            'typescript 마이그레이션',
            'storybook mdx 도입',
        ],
    },
    {
        title: 'Step-IT',
        startDate: '2023-03-03',
        endDate: '2023-06-14',
        skills: ['Typescript', 'Java', 'ReactNative', 'recoil', 'styled-components', 'Git', 'Github'],
        contents: ['next 기반의 SSR 웹 애플리케이션 구축', 'BEM 방법론을 적용하여 styled components 사용'],
    },
    {
        title: 'KCOOK',
        startDate: '2022-07-01',
        endDate: '2022-10-31',
        skills: ['Typescript', 'React', 'SCSS', 'Git', 'Github'],
        contents: ['로딩페이지 뷰 변경', 'overlay transition 개선', '플러그인 관리 페이지 table 뷰 개선 및 번역 추가'],
    },
    {
        title: 'Pick-IT',
        startDate: '2022-03-03',
        endDate: '2022-06-16',
        skills: ['Javascript', 'React', 'SCSS'],
        contents: ['newtab extension 개발', 'popup extension 개발', 'extension에 맞는 웹팩 셋팅'],
    },
    {
        title: 'Seasons',
        startDate: '2021-03-03',
        endDate: '2021-06-16',
        skills: ['Javascript', 'jQuery', 'HTML', 'CSS'],
        contents: [
            '채소를 검색하여 장바구니에 담는 페이지 개발',
            '장바구니의 채소들에 대해 커머스 별로 가격을 보여주는 페이지 개발',
        ],
    },
] as const;
